<!-- sidebar -->
        <div class="sidebar">
        
            <div class="sidebar_inner" data-simplebar>
        
                <ul>
                    <li class="active"><a href="#"> 
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="text-blue-600"> 
                            <path d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z" />
                        </svg>
                        <span> Beranda </span> </a> 
                    </li>
                </ul>
                
                <h3 class="side-title"> Contributor </h3>

                <div class="contact-list my-2 ml-1">
                    
                    <a href="#">
                        <div class="contact-avatar">
                            <img src="<?php echo $rid['site_url'];?>/template/<?php echo $rid['template'];?>/assets/images/avatars/avatar-1.jpg" alt="">
                            <span class="user_status status_online"></span>
                        </div>
                        <div class="contact-username"> Joseph</div>
                    </a>
                    <a href="#">
                        <div class="contact-avatar">
                            <img src="<?php echo $rid['site_url'];?>/template/<?php echo $rid['template'];?>/assets/images/avatars/avatar-2.jpg" alt="">
                            <span class="user_status"></span>
                        </div>
                        <div class="contact-username"> Ari martana</div>
                    </a>
    
                </div>

                <div class="footer-links">
                    <a href="#">About</a>
                    <a href="#">Contact Us </a>
                    <a href="#">Developer</a>
                    <a href="#">Terms of service</a>
                </div>
 
            </div>

            <!-- sidebar overly for mobile -->
            <div class="side_overly" uk-toggle="target: #wrapper ; cls: is-collapse is-active"></div>

        </div> 