 <!-- Header -->
        <header>
            <div class="header_wrap">
                <div class="header_inner mcontainer">
                    <div class="left_side">
                        
                        <span class="slide_menu" uk-toggle="target: #wrapper ; cls: is-collapse is-active">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path d="M3 4h18v2H3V4zm0 7h12v2H3v-2zm0 7h18v2H3v-2z" fill="currentColor"></path></svg>
                        </span>

                        <div id="logo">
                            <a href="<?php echo $rid['site_url'];?>" data-ajax="?link1=beranda"> 
                                <img src="https://waysender-v2.ridped.com/community/themes/waynetwork/img/logo.png?cache=523" alt="">
                                <img src="https://waysender-v2.ridped.com/community/themes/waynetwork/img/logo.png?cache=523" class="logo_mobile" alt="">
                            </a>
                        </div>
                    </div>
                     
                  <!-- search icon for mobile -->
                    <div class="header-search-icon" uk-toggle="target: #wrapper ; cls: show-searchbox"> </div>
                    <div class="header_search"><i class="uil-search-alt"></i> 
                        <input value="" type="text" class="form-control" placeholder="Search for Friends , Videos and more.." autocomplete="off">
                    </div>
    
                    <div class="right_side">
    
                        <div class="header_widgets">
                            <a href="https://github.com/ridped/s-network" class="is_link">  Download / Join </a>   

                            <a href="#" class="is_icon" uk-tooltip="title: Notifications">
                                <svg fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M10 2a6 6 0 00-6 6v3.586l-.707.707A1 1 0 004 14h12a1 1 0 00.707-1.707L16 11.586V8a6 6 0 00-6-6zM10 18a3 3 0 01-3-3h6a3 3 0 01-3 3z"></path></svg>
                                <span> </span>
                            </a>
                            <div uk-drop="mode: click" class="header_dropdown">
                                 <div  class="dropdown_scrollbar" data-simplebar>
                                     <div class="drop_headline">
                                         <h4>Notifications </h4>
                                         <div class="btn_action">
                                            <a href="#" data-tippy-placement="left" title="Notifications">
                                                <ion-icon name="settings-outline"></ion-icon>
                                            </a>
                                            <a href="#" data-tippy-placement="left" title="Mark as read all">
                                                <ion-icon name="checkbox-outline"></ion-icon>
                                            </a>
                                        </div>
                                     </div>
                                     <ul>
                                         COMING SOON!
                                     </ul> 
                                 </div>
                            </div> 

                            <!-- Message -->
                            <a href="#" class="is_icon" uk-tooltip="title: Message" id="icon_head_msg">
                                <svg fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 5v8a2 2 0 01-2 2h-5l-5 4v-4H4a2 2 0 01-2-2V5a2 2 0 012-2h12a2 2 0 012 2zM7 8H5v2h2V8zm2 0h2v2H9V8zm6 0h-2v2h2V8z" clip-rule="evenodd"></path></svg>
                                <span> </span>
                            </a>
                            <div uk-drop="mode: click" class="header_dropdown is_message" id="icon_head_msg_content">
                                <div  class="dropdown_scrollbar" data-simplebar>
                                    <div class="drop_headline">
                                         <h4>Messages </h4>
                                        <div class="btn_action">
                                            <a hidden href="#" data-tippy-placement="left" title="Notifications">
                                                <ion-icon name="settings-outline" uk-tooltip="title: Message settings ; pos: left"></ion-icon>
                                            </a>
                                            <a  hidden href="#" data-tippy-placement="left" title="Mark as read all">
                                                <ion-icon name="checkbox-outline"></ion-icon>
                                            </a>
                                        </div>
                                    </div>
                                    <input hidden type="text" class="uk-input" placeholder="Search in Messages">
                                    <ul class="rid_chathead">
                                        <?php
                                           $dataC = getChats();
                                           if ($dataC !== false) {
                                                while ($row = mysqli_fetch_assoc($dataC)) {
                                                    $dataU = getDataUser($row['c_with']);
                                                    $getLastMsg = getMsgs($row['c_with'], $row['id_user'], 1);
                                                    if ($getLastMsg !== false) {
                                                        $getLastMsg = $getLastMsg->fetch_assoc();
                                                    }
                                         ?>
                                        <li class="" id="chatid-head-<?= $row['c_with'];?>">
                                            <a href="#" rid-ajax="?link1=messages&uid=<?= $row['c_with'];?>">
                                                <div class="drop_avatar"> <img src="<?php echo $rid['site_url'];?>/template/<?php echo $rid['template'];?>/assets/images/avatars/avatar-7.jpg" alt="">
                                                </div>
                                                <div class="drop_text">
                                                    <strong> <?= $dataU['full_name'];?> </strong>
                                                    <p id="lastmsg-head-<?= $row['c_with'];?>">
                                                        <?php echo $getLastMsg['from_id'] == $row['id_user'] ? 'You: ' . $getLastMsg['text'] : $getLastMsg['text'];?>
                                                    </p>
                                                </div>
                                            </a>
                                        </li>
                                        <?php } } ?>
                                    </ul>
                                </div>
                                <a href="#" class="see-all" rid-ajax="?link1=messages"> See all </a>
                            </div>
         
        
                            <a href="#">
                                <img src="https://waysender-v2.ridped.com/community/themes/waynetwork/img/logo.png?cache=523" class="is_avatar" alt="">
                            </a>
                            <div uk-drop="mode: click;offset:5" class="header_dropdown profile_dropdown">

                                <a href="<?php echo $rid['site_url'];?>/index.php?link1=profile&uid=<?php echo $rid['dataUser']['id'];?>" rid-ajax="?link1=profile&uid=<?php echo $rid['dataUser']['id'];?>" class="user">
                                    <div class="user_avatar">
                                        <img src="https://waysender-v2.ridped.com/community/themes/waynetwork/img/logo.png?cache=523" alt="">
                                    </div>
                                    <div class="user_name">
                                        <div> <?php echo $rid['dataUser']['full_name'];?> </div>
                                        <span> @<?php echo $rid['dataUser']['rid_username'];?></span>
                                    </div>
                                </a>
                                <a href="#">
                                    <svg fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M11.49 3.17c-.38-1.56-2.6-1.56-2.98 0a1.532 1.532 0 01-2.286.948c-1.372-.836-2.942.734-2.106 2.106.54.886.061 2.042-.947 2.287-1.561.379-1.561 2.6 0 2.978a1.532 1.532 0 01.947 2.287c-.836 1.372.734 2.942 2.106 2.106a1.532 1.532 0 012.287.947c.379 1.561 2.6 1.561 2.978 0a1.533 1.533 0 012.287-.947c1.372.836 2.942-.734 2.106-2.106a1.533 1.533 0 01.947-2.287c1.561-.379 1.561-2.6 0-2.978a1.532 1.532 0 01-.947-2.287c.836-1.372-.734-2.942-2.106-2.106a1.532 1.532 0 01-2.287-.947zM10 13a3 3 0 100-6 3 3 0 000 6z" clip-rule="evenodd"></path></svg>
                                    My Account 
                                </a>
                                <a href="#" id="night-mode" class="btn-night-mode">
                                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                                        <path d="M17.293 13.293A8 8 0 016.707 2.707a8.001 8.001 0 1010.586 10.586z" />
                                      </svg>
                                     Night mode
                                    <span class="btn-night-mode-switch">
                                        <span class="uk-switch-button"></span>
                                    </span>
                                </a>
                                <a href="<?php echo $rid['site_url'];?>/index.php?link1=logout">
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path>
                                    </svg>
                                    Log Out 
                                </a>

                                
                            </div>

                        </div>
                        
                    </div>
                </div>
            </div>
        </header>