<div class="message-bubble <?php echo $rid['data_chat']['from_id'] == $rid['dataUser']['id'] ? 'me' : '';?>">
	<div class="message-bubble-inner">
        <div class="message-avatar"><img src="https://waysender-v2.ridped.com/community/themes/waynetwork/img/logo.png?cache=523" alt=""></div>
        <div class="message-text ridmessage"><p><?php echo $rid['data_chat']['text'];?></p></div>
    </div>
	<div class="clearfix"></div>
</div>