<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Favicon -->
    <link href="<?php echo $rid['site_url'];?>/template/<?php echo $rid['template'];?>/assets/images/favicon.png" rel="icon" type="image/png">

    <!-- Basic Page Needs
        ================================================== -->
    <title><?php echo $rid['title'];?></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="<?php echo $rid['title'];?> still beta, come join with our community now!.">

    <!-- icons
    ================================================== -->
    <link rel="stylesheet" href="<?php echo $rid['site_url'];?>/template/<?php echo $rid['template'];?>/assets/css/icons.css">

    <!-- CSS 
    ================================================== --> 
    <link rel="stylesheet" href="<?php echo $rid['site_url'];?>/template/<?php echo $rid['template'];?>/assets/css/uikit.css">
    <link rel="stylesheet" href="<?php echo $rid['site_url'];?>/template/<?php echo $rid['template'];?>/assets/css/style.css">
     <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet"> 
     <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/4.3.0/jquery.form.min.js?v=<?php echo time();?>" integrity="sha384-qlmct0AOBiA2VPZkMY3+2WqkHtIQ9lSdAsAn5RUJD/3vA5MKDgSGcdmIv4ycVxyn" crossorigin="anonymous"></script>
     <script>
         function rid_ajaxFileLoad() {
             return "<?php echo $rid['site_url'];?>/ajaxFileLoad.php";
         }
         function rid_requestFile() {
             return "<?php echo $rid['site_url'];?>/req.php";
         }
     </script>


</head> 
<body>
   
    <?php if ($rid['loggedin']) { ?>
    <div id="wrapper">

       <?php echo rid_LoadPage('header/main');?>
       <?php echo rid_LoadPage('sidebar/main');?>

        <!-- Main Contents -->
        <div class="main_content">
            <?php echo $rid['content'];?>
        </div>
    </div>
    <?php } else { ?>
    <?php echo $rid['content'];?>
    <?php } ?>
 
    <!-- For Night mode -->
    <script>
        (function (window, document, undefined) {
            'use strict';
            if (!('localStorage' in window)) return;
            var nightMode = localStorage.getItem('gmtNightMode');
            if (nightMode) {
                document.documentElement.className += ' night-mode';
            }
        })(window, document);
    
        (function (window, document, undefined) {
    
            'use strict';
    
            // Feature test
            if (!('localStorage' in window)) return;
    
            // Get our newly insert toggle
            var nightMode = document.querySelector('#night-mode');
            if (!nightMode) return;
    
            // When clicked, toggle night mode on or off
            nightMode.addEventListener('click', function (event) {
                event.preventDefault();
                document.documentElement.classList.toggle('dark');
                if (document.documentElement.classList.contains('dark')) {
                    localStorage.setItem('gmtNightMode', true);
                    return;
                }
                localStorage.removeItem('gmtNightMode');
            }, false);
    
        })(window, document);
    </script>
  
    <!-- Javascript
    ================================================== -->
    <script src="<?php echo $rid['site_url'];?>/template/<?php echo $rid['template'];?>/assets/js/tippy.all.min.js"></script>
    <script src="<?php echo $rid['site_url'];?>/template/<?php echo $rid['template'];?>/assets/js/uikit.js"></script>
    <script src="<?php echo $rid['site_url'];?>/template/<?php echo $rid['template'];?>/assets/js/simplebar.js"></script>
    <script src="<?php echo $rid['site_url'];?>/template/<?php echo $rid['template'];?>/assets/js/custom.js"></script>
    <script src="<?php echo $rid['site_url'];?>/template/<?php echo $rid['template'];?>/assets/js/bootstrap-select.min.js"></script>
    <script src="https://unpkg.com/ionicons@5.2.3/dist/ionicons.js"></script>

</body>
</html>