<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Favicon -->
    <link href="<?php echo $rid['site_url'];?>/template/<?php echo $rid['template'];?>/assets/images/favicon.png" rel="icon" type="image/png">

    <!-- Basic Page Needs
        ================================================== -->
    <title><?php echo $rid['title'];?></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="<?php echo $rid['title'];?> still beta, come join with our community now!.">

    <!-- icons
    ================================================== -->
    <link rel="stylesheet" href="<?php echo $rid['site_url'];?>/template/<?php echo $rid['template'];?>/assets/css/icons.css">

    <!-- CSS 
    ================================================== --> 
    <link rel="stylesheet" href="<?php echo $rid['site_url'];?>/template/<?php echo $rid['template'];?>/assets/css/uikit.css">
    <link rel="stylesheet" href="<?php echo $rid['site_url'];?>/template/<?php echo $rid['template'];?>/assets/css/style.css?v=<?php echo time();?>">
     <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet"> 
     <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/4.3.0/jquery.form.min.js?v=<?php echo time();?>" integrity="sha384-qlmct0AOBiA2VPZkMY3+2WqkHtIQ9lSdAsAn5RUJD/3vA5MKDgSGcdmIv4ycVxyn" crossorigin="anonymous"></script>
     <script src="https://cdn.socket.io/4.6.0/socket.io.min.js" integrity="sha384-c79GN5VsunZvi+Q/WObgk2in0CbZsHnjEqvFxC5DxHn9lTfNce2WW6h2pH6u/kF+" crossorigin="anonymous"></script>
     <script src="<?php echo $rid['template_url'];?>/javascript/rid_script.js?v=<?php echo time();?>"></script>
     <style>
        .ridmessage {
            white-space: pre-wrap;
        }
    </style>

     <script>
        function comingsun() {
            alert('Coming soon!');
        }
         function rid_ajaxFileLoad() {
             return "<?php echo $rid['site_url'];?>/ajaxFileLoad.php";
         }
         function rid_requestFile() {
             return "<?php echo $rid['site_url'];?>/req.php";
         }
         function base_url() {
            return "<?php echo $rid['site_url'];?>";
         }
         <?php if ($rid['ssl'] === true) { ?>
         const socket = io("https://<?php echo $rid['without_http'];?>:<?php echo $rid['port_app'];?>");
         <?php } else { ?>
         const socket = io("http://<?php echo $rid['without_http'];?>:<?php echo $rid['port_app'];?>");
         <?php } ?>
         username = "<?php echo $rid['loggedin'] ? $rid['dataUser']['rid_username'] : false;?>";
         uid = "<?php echo $rid['loggedin'] ? $rid['dataUser']['id'] : false;?>";
         is_page = "<?php echo $_GET['link1'];?>";
         socket.emit("connected", uid);
         $(document).on('click', 'a[rid-ajax]', function(e) {
               var contentnya = $('.main_content');
               var ISAPI = false;
               var url = $(this).attr('rid-ajax');
               e.preventDefault();
               if (!ISAPI) {
                 $.post(rid_ajaxFileLoad() + url, {url:url}, function (data) {
                     var json_data = JSON.parse($(data).filter('#json-data').val());
                     if (json_data.redirect == true) {
                        return window.location.href = json_data.redirect_url;
                     }
                     contentnya.html(data);
                     document.title = json_data.title;
                     if (json_data.is_beranda) {
                        window.history.pushState({state:'new'},'', base_url());
                     } else {
                        window.history.pushState({state:'new'},'', base_url() + '/index.php' + url);
                     }
                     is_page = json_data.is_page;
                     $("html, body").animate({ scrollTop: 0 }, 150);
                 }).fail(function() {
                    alert('Oops!')
                  })
                  .always(function() {
                    $("html, body").animate({ scrollTop: 0 }, 150);
                  });
               }
           });
     </script>


</head> 
<body>
   
    <?php if ($rid['loggedin']) { ?>
    <div id="wrapper">

       <?php echo rid_LoadPage('header/main');?>
       <?php echo rid_LoadPage('sidebar/main');?>

        <!-- Main Contents -->
        <div class="main_content">
            <?php echo $rid['content'];?>
        </div>
    </div>
    <?php } else { ?>
    <?php echo $rid['content'];?>
    <?php } ?>

    <audio hidden id="sound_typing">
      <source src="<?php echo $rid['template_url'];?>/ringtones/typing_messenger.mp3" type="audio/mpeg">
    Your browser does not support the audio element.
    </audio>
    <audio hidden id="sound_pop">
      <source src="<?php echo $rid['template_url'];?>/ringtones/pop.mp3" type="audio/mpeg">
    Your browser does not support the audio element.
    </audio>
    <audio hidden id="sound_new_msg">
      <source src="<?php echo $rid['template_url'];?>/ringtones/new_msg.mp3" type="audio/mpeg">
    Your browser does not support the audio element.
    </audio>
 
    <!-- For Night mode -->
    <script>
        (function (window, document, undefined) {
            'use strict';
            if (!('localStorage' in window)) return;
            var nightMode = localStorage.getItem('gmtNightMode');
            if (nightMode) {
                document.documentElement.className += ' night-mode';
            }
        })(window, document);
    
        (function (window, document, undefined) {
    
            'use strict';
    
            // Feature test
            if (!('localStorage' in window)) return;
    
            // Get our newly insert toggle
            var nightMode = document.querySelector('#night-mode');
            if (!nightMode) return;
    
            // When clicked, toggle night mode on or off
            nightMode.addEventListener('click', function (event) {
                event.preventDefault();
                document.documentElement.classList.toggle('dark');
                if (document.documentElement.classList.contains('dark')) {
                    localStorage.setItem('gmtNightMode', true);
                    return;
                }
                localStorage.removeItem('gmtNightMode');
            }, false);
    
        })(window, document);
    </script>
  
    <!-- Javascript
    ================================================== -->
    <script src="<?php echo $rid['template_url'];?>/javascript/rid_socket.js?v=<?php echo time();?>"></script>
    <script src="<?php echo $rid['site_url'];?>/template/<?php echo $rid['template'];?>/assets/js/tippy.all.min.js"></script>
    <script src="<?php echo $rid['site_url'];?>/template/<?php echo $rid['template'];?>/assets/js/uikit.js"></script>
    <script src="<?php echo $rid['site_url'];?>/template/<?php echo $rid['template'];?>/assets/js/simplebar.js"></script>
    <script src="<?php echo $rid['site_url'];?>/template/<?php echo $rid['template'];?>/assets/js/custom.js"></script>
    <script src="<?php echo $rid['site_url'];?>/template/<?php echo $rid['template'];?>/assets/js/bootstrap-select.min.js"></script>
    <script src="https://unpkg.com/ionicons@5.2.3/dist/ionicons.js"></script>

</body>
</html>