<div class="card lg:mx-0 uk-animation-slide-bottom-small post-id-<?php echo $rid['datapost']['id'];?>">

                
                            <?php echo rid_LoadPage('post/post_header');?>
                            <div class="p-5 pt-0 border-b dark:border-gray-700">
                
                                <span class="ridmessage"><?php echo $rid['datapost']['postText'];?></span>
                
                            </div>
                            
                
                            <div class="p-4 space-y-3"> 
                                
                                <div class="flex space-x-4 lg:font-bold">
                                    <a href="#" class="flex items-center space-x-2" onclick="rid_LikePost(`<?php echo $rid['datapost']['id'];?>`)">
                                        <div class="p-2 rounded-full  text-black lg:bg-gray-100 dark:bg-gray-600 ">
                                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" width="22" height="22" class="dark:text-gray-100">
                                                <path d="M2 10.5a1.5 1.5 0 113 0v6a1.5 1.5 0 01-3 0v-6zM6 10.333v5.43a2 2 0 001.106 1.79l.05.025A4 4 0 008.943 18h5.416a2 2 0 001.962-1.608l1.2-6A2 2 0 0015.56 8H12V4a2 2 0 00-2-2 1 1 0 00-1 1v.667a4 4 0 01-.8 2.4L6.8 7.933a4 4 0 00-.8 2.4z" />
                                            </svg>
                                        </div>
                                        <div class="">Like</div>
                                    </a>
                                </div>   
                            </div>
                        </div>