<div class="flex justify-between items-center lg:p-4 p-2.5">
                                <div class="flex flex-1 items-center space-x-4">
                                    <a href="feed.html#">
                                        <img src="https://waysender-v2.ridped.com/community/themes/waynetwork/img/logo.png?cache=523" class="bg-gray-200 border border-white rounded-full w-10 h-10">
                                    </a>
                                    <div class="flex-1 font-semibold capitalize">
                                        <a href="feed.html#" class="text-black dark:text-gray-100"><?php echo $rid['datauserpost']['full_name'];?></a>
                                    </div>
                                </div>
                                <div>
                                <a href="#"> <i class="icon-feather-more-horizontal text-2xl hover:bg-gray-200 rounded-full p-2 transition -mr-1 dark:hover:bg-gray-700"></i> </a>
                                <div class="bg-white w-56 shadow-md mx-auto p-2 mt-12 rounded-md text-gray-500 hidden text-base border border-gray-100 dark:bg-gray-900 dark:text-gray-100 dark:border-gray-700" 
                                uk-drop="mode: click;pos: bottom-right;animation: uk-animation-slide-bottom-small">
                                
                                    <ul class="space-y-1">
                                        <li> 
                                            <a href="feed.html#" class="flex items-center px-3 py-2 text-red-500 hover:bg-red-100 hover:text-red-500 rounded-md dark:hover:bg-red-600">
                                            <i class="uil-trash-alt mr-1"></i>  Delete
                                            </a> 
                                        </li>
                                    </ul>
                                
                                </div>
                                </div>
                            </div>